### NumPy : Practice Problems 1

In [1]:
import numpy as np

In [2]:
#1.Write a NumPy program to get the numpy version and show numpy build configuration
print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


In [ ]:
#2.Create a null vector of size 10 but the fifth value which is 1
n = np.zeros(10)
n[4] = 1
print(n)

In [5]:
#2-.Create a vector with values ranging from 10 to 49
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
#3.create two arrays and stack them vertically
a1 = np.random.randint(1,5,(3,3))
a2 = np.random.randint(6,10,(3,3))
np.vstack([a1,a2])


array([[1, 1, 2],
       [3, 2, 1],
       [2, 2, 3],
       [6, 7, 6],
       [7, 7, 6],
       [6, 7, 8]])

In [22]:
#4.Reverse a vector (first element becomes last)
a1 = np.array([1,10,25,70])
a1[::-1]

array([70, 25, 10,  1])

In [23]:
#5.Create a 3x3 matrix with values ranging from 0 to 8
np.random.randint(0,9,(3,3))

array([[2, 5, 2],
       [8, 6, 7],
       [3, 7, 0]])

In [25]:
#6.Find indices of non-zero elements from [1,2,0,0,4,0]
a = [1,2,0,0,4,0]
np.nonzero(a)


(array([0, 1, 4], dtype=int64),)

In [30]:
#7.Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.randint(0,100,(10,10))
print(x.min())
print(x.max())


0
97


In [38]:
#8. Create a random vector of size 30 and find the mean value
y = np.random.randint(0,100,(30))
print(y.mean())

50.03333333333333


In [39]:
#9.Create a 2d array with 1 on the border and 0 inside
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [49]:
#10.How to add a border (filled with 0's) around an existing array
y = np.random.randint(1,10)
z = np.zeros((10,10))
z[1:-1,1:-1] = y
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [50]:
#11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
y = np.zeros((5,5))
y[1:2,:1]=1
y[2:3,1:2]=2
y[3:4,2:3]=3
y[4:5,3:4]=4
print(y)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
#12.Create a 5*5 matrix with random values and normalize it
