### NumPy

In [2]:
import numpy as np

In [4]:
a = np.zeros(3)
print(a)


[0. 0. 0.]


In [6]:
b = np.zeros((3,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
c = np.zeros((3,3,3))
print(c.shape)


(3, 3, 3)


In [12]:
d = np.ones((3,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
z = np.full((3,3),"hello")
z.size

9

In [9]:
np.random.randint(1,5,(3,3))

array([[4, 3, 3],
       [1, 2, 3],
       [4, 4, 2]])

In [13]:
np.random.rand()

0.13457082340368742

In [22]:
r = np.array([10,11,12])
print(r.shape)
print(r.ndim)
print(r.size)

(3,)
1
3


In [4]:
data = np.random.randint(100,200,(5,4,3))
data

array([[[111, 143, 181],
        [145, 172, 131],
        [153, 176, 133],
        [199, 159, 141]],

       [[124, 167, 184],
        [195, 125, 169],
        [132, 108, 123],
        [178, 148, 126]],

       [[160, 157, 113],
        [181, 195, 113],
        [180, 104, 135],
        [172, 151, 159]],

       [[170, 165, 129],
        [162, 181, 147],
        [110, 197, 199],
        [198, 133, 137]],

       [[174, 161, 173],
        [118, 160, 118],
        [164, 112, 139],
        [135, 130, 105]]])

### Accessing data in numpy


In [31]:
data[:4,2:]

array([[149, 151],
       [115, 115],
       [148, 153],
       [112, 175]])

In [17]:
np.random.rand(3,3)

array([[0.30554418, 0.19361671, 0.63703553],
       [0.72472094, 0.35223714, 0.98601756],
       [0.99950896, 0.02950806, 0.79097258]])

### Reshaping

In [42]:
d2 = np.arange(10)

In [45]:
d2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
d2.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [47]:
d2.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Splitting & Stacking

In [48]:
d3 = np.random.randint(100,200,(5,4))

In [50]:
a,b = np.hsplit(d3,2)

In [51]:
a

array([[116, 137],
       [168, 171],
       [199, 146],
       [109, 185],
       [132, 194]])

In [52]:
b

array([[125, 141],
       [177, 142],
       [143, 107],
       [123, 198],
       [108, 180]])

In [54]:
c,e = np.vsplit(d3,[2])

In [55]:
c

array([[116, 137, 125, 141],
       [168, 171, 177, 142]])

In [56]:
e

array([[199, 146, 143, 107],
       [109, 185, 123, 198],
       [132, 194, 108, 180]])

In [57]:
np.hstack([a,b])

array([[116, 137, 125, 141],
       [168, 171, 177, 142],
       [199, 146, 143, 107],
       [109, 185, 123, 198],
       [132, 194, 108, 180]])

In [59]:
np.vstack([c,e])

array([[116, 137, 125, 141],
       [168, 171, 177, 142],
       [199, 146, 143, 107],
       [109, 185, 123, 198],
       [132, 194, 108, 180]])