### NumPy Test

In [2]:
import numpy as np

In [7]:
import collections as col

### 1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [10]:
a = np.random.randint(1,100,(3,3))
print(col.Counter(a.flatten()))

Counter({2: 2, 33: 2, 46: 1, 86: 1, 98: 1, 47: 1, 10: 1})


### 2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function

In [11]:
n = np.arange(9)
n.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 3. How to find the memory size of any array

In [12]:
n = np.random.randint(1,100,(3,3))
s = n.size * n.itemsize
s

36

### 4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside

In [21]:
o = np.full((10,10),1)
o[1:-1,1:-1] = 0
o

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 5.Create a 8x8 matrix and fill it with a checkerboard pattern

In [23]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 6. Normalize a 5x5 random matrix

In [26]:
a = np.random.randint(1,100,(3,3))
b = ((a-a.mean())/a.std())
b

array([[ 0.890859  , -1.23833097, -1.40467394],
       [ 0.25875573,  0.3918301 ,  0.69124744],
       [ 1.12373915, -1.47121113,  0.75778463]])

###  7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place

In [31]:
arr = np.arange(0,11)
c = np.where((arr>3) & (arr<8))
c

(array([4, 5, 6, 7], dtype=int64),)

### 8. How to get the dates of yesterday, today and tomorrow?

In [34]:
today   = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow =  today + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2020-02-13
2020-02-14
2020-02-15


### 9. Generate two arrays of size 2X4 & 3X3, find difference between them

### error

In [51]:
n = np.full((2,4),np.arange(4))
n
n2 = np.full((3,3),np.arange(3))
n2
# np.diff(n,n2)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

### 10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value 

In [17]:
a = np.arange(100)
choices = ['cat','dog','rat']
# np.choose(a, choices)

### 11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

### Confused

In [27]:
a = np.zeros(10)

a[1] = 1
a[3] = 1
a[5] = 1
a[7] = 1
a[9] = 1
a


array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1.])

### 12. Given a two dimensional array, how to extract unique rows?

In [29]:
original_array = np.random.randint(1,100,(2,2))
unique_rows = np.unique(original_array, axis=0)
unique_rows

array([[93, 82],
       [97, 41]])

### 13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

In [32]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
Z

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

### 14. How to find the closest value (to a given scalar) in a vector?