### NumPy : Practice Problems 1

In [4]:
import numpy as np

In [2]:
#1.Write a NumPy program to get the numpy version and show numpy build configuration
print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


In [ ]:
#2.Create a null vector of size 10 but the fifth value which is 1
n = np.zeros(10)
n[4] = 1
print(n)

In [5]:
#2-.Create a vector with values ranging from 10 to 49
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
#3.create two arrays and stack them vertically
a1 = np.random.randint(1,5,(3,3))
a2 = np.random.randint(6,10,(3,3))
np.vstack([a1,a2])


array([[1, 1, 2],
       [3, 2, 1],
       [2, 2, 3],
       [6, 7, 6],
       [7, 7, 6],
       [6, 7, 8]])

In [22]:
#4.Reverse a vector (first element becomes last)
a1 = np.array([1,10,25,70])
a1[::-1]

array([70, 25, 10,  1])

In [23]:
#5.Create a 3x3 matrix with values ranging from 0 to 8
np.random.randint(0,9,(3,3))

array([[2, 5, 2],
       [8, 6, 7],
       [3, 7, 0]])

In [25]:
#6.Find indices of non-zero elements from [1,2,0,0,4,0]
a = [1,2,0,0,4,0]
np.nonzero(a)


(array([0, 1, 4], dtype=int64),)

In [30]:
#7.Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.randint(0,100,(10,10))
print(x.min())
print(x.max())


0
97


In [38]:
#8. Create a random vector of size 30 and find the mean value
y = np.random.randint(0,100,(30))
print(y.mean())

50.03333333333333


In [39]:
#9.Create a 2d array with 1 on the border and 0 inside
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [49]:
#10.How to add a border (filled with 0's) around an existing array
y = np.random.randint(1,10)
z = np.zeros((10,10))
z[1:-1,1:-1] = y
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
#11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
y = np.zeros((5,5))
y
y[1,0]=1
y[2,1]=2
y[3,2]=3
y[4,3]=4
y

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

### error

In [13]:
#12.Create a 5*5 matrix with random values and normalize it
a = np.random.random((5,5))
a
# normalization
# b= (a - a.min())/(a.max()-a.min())
# b



array([[0.08442101, 0.83114254, 0.0984784 , 0.85875615, 0.29992103],
       [0.56020412, 0.67606733, 0.66889117, 0.56920515, 0.69885403],
       [0.58681779, 0.39100629, 0.63613628, 0.48198361, 0.38850542],
       [0.52069689, 0.93167091, 0.37884411, 0.19313906, 0.48047537],
       [0.51045624, 0.50864236, 0.99811291, 0.78991467, 0.08924913]])

In [15]:
#13.How to find common values between two arrays
array1= np.array([1,2,3,4,5,6])
array2= np.array([2,4,6,8,10])
np.intersect1d(array1, array2)

array([2, 4, 6])

In [16]:
a1 = np.arange(25)
a2 = np.arange(10,51)
np.intersect1d(a1, a2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#14. Consider a generator function that generates 10 integers and use it to build an array
def generator():
    